name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

# 👉 เพิ่มบล็อกนี้
permissions:
  contents: write          # ให้ workflow ผลัก (push) โค้ดได้

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Generate static site
        run: pnpm generate      # หรือ pnpm run generate

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .output/public
